### ISSUE TITLE
will  acuitylite support onnx model + calibration cache format?

### ISSUE THREAD

**Issue by zjd1988** [VeriSilicon/acuitylite#12]

**Comment by lileiigithub** [comment]
Hi, Acuitylite 6.12.0 could support the Onnx model, you can try the newest Acuitylite by the command: pip install acuitylite.
And the demo is here https://github.com/VeriSilicon/acuitylite/blob/main/demo/squeezenet_onnx_test.py.

**Comment by zjd1988** [comment]
@lileiigithub  thanks, actually I want to import quant parameter from QAT

**Comment by geneyoung** [comment]
AcuityLite can support QAT onnx model with a layer enclosed with Qauntize layer and Dequantize layer，AcuityLite also can limited support some quantze layer such as QLinearConv. Could you please try the newest version and file issue if you meet some problems, it is appreciated if you can attach your part of model so that we can reproduce your problem.
